# Complete SD-Core UPF Package Example
# This directory structure shows how to organize Interface resources for Nephio

---
# interfaces.yaml
# Interface resources for SD-Core UPF

apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n3
  namespace: upf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.upf
  labels:
    nephio.org/interface: n3
    nephio.org/nf: upf
spec:
  networkInstance:
    name: vpc-ran
  cniType: macvlan
  attachmentType: vlan

---
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n6
  namespace: upf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.upf
  labels:
    nephio.org/interface: n6
    nephio.org/nf: upf
spec:
  networkInstance:
    name: vpc-internet
  cniType: macvlan
  attachmentType: vlan

---
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n4
  namespace: upf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.upf
  labels:
    nephio.org/interface: n4
    nephio.org/nf: upf
spec:
  networkInstance:
    name: vpc-internal
  cniType: macvlan
  attachmentType: vlan

---
# network-instances.yaml
# NetworkInstance resources defining network pools

apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-ran
  namespace: upf
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    nephio.org/network: ran
spec:
  name: vpc-ran
  interfaces:
  - kind: bridgedomain
  - kind: interface
    selector:
      matchLabels:
        nephio.org/interface: n3
  pools:
  - name: n3-ipv4-pool
    prefixLength: 24

---
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-internet
  namespace: upf
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    nephio.org/network: internet
spec:
  name: vpc-internet
  interfaces:
  - kind: bridgedomain
  - kind: interface
    selector:
      matchLabels:
        nephio.org/interface: n6
  pools:
  - name: n6-ipv4-pool
    prefixLength: 24

---
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-internal
  namespace: upf
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    nephio.org/network: internal
spec:
  name: vpc-internal
  interfaces:
  - kind: bridgedomain
  - kind: interface
    selector:
      matchLabels:
        nephio.org/interface: n4
  pools:
  - name: n4-ipv4-pool
    prefixLength: 24

---
# workload-cluster.yaml
# WorkloadCluster context information

apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: edge-cluster-1
  namespace: upf
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  clusterName: edge-cluster-1
  cnis:
  - macvlan
  - sriov
  masterInterface: ens3  # Physical interface for MacVLAN

---
# package-context.yaml
# Package context for kpt

apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  name: upf-edge-cluster-1

---
# Kptfile
# Pipeline configuration

apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: upf-package
  annotations:
    config.kubernetes.io/local-config: "true"
info:
  description: SD-Core UPF deployment package with Nephio Interface resources
  
  # Readiness gates ensure package isn't deployed until all conditions are met
  readinessGates:
  # WorkloadCluster injection - ensures cluster-specific config is available
  - conditionType: config.injection.WorkloadCluster.workload-cluster
  
  # Interface processing - one per Interface resource
  - conditionType: req.nephio.org.interface.n3
  - conditionType: req.nephio.org.interface.n6
  - conditionType: req.nephio.org.interface.n4
  
  # IP allocation - one per IPClaim (auto-created by interface-fn)
  - conditionType: ipam.nephio.org.ipclaim.n3
  - conditionType: ipam.nephio.org.ipclaim.n6
  - conditionType: ipam.nephio.org.ipclaim.n4

pipeline:
  mutators:
  # interface-fn creates IPClaim resources from Interface resources
  - image: docker.io/nephio/interface-fn:v2.0.0
    configMap:
      debug: "true"
  
  # nad-fn generates NetworkAttachmentDefinitions
  - image: docker.io/nephio/nad-fn:v2.0.0
    configMap:
      debug: "true"
  
  # Apply any additional transformations
  - image: gcr.io/kpt-fn/apply-setters:v0.2
    configPath: setters.yaml
  
  validators:
  # Validate all resources
  - image: gcr.io/kpt-fn/kubeval:v0.3.0
    configMap:
      ignore_missing_schemas: "true"

# NOTE: status section is AUTO-GENERATED by Nephio controllers
# Do NOT manually write the status section in your initial Kptfile
# It will be added automatically as conditions are evaluated

---
# setters.yaml
# Configuration setters for customization

apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  cluster-name: edge-cluster-1
  namespace: upf
  master-interface: ens3
