# Complete OAI Split CU/DU Package Example
# Separate packages for CU and DU deployment

################################################################################
# CU (Central Unit) Package
################################################################################

---
# cu-interfaces.yaml
# Interface resources for OAI CU

apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n2
  namespace: oai-cu
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.cu
  labels:
    nephio.org/interface: n2
    nephio.org/nf: cu
    nephio.org/deployment-type: split
spec:
  networkInstance:
    name: vpc-control
  cniType: macvlan
  attachmentType: vlan

---
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: f1c
  namespace: oai-cu
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.cu
  labels:
    nephio.org/interface: f1c
    nephio.org/nf: cu
    nephio.org/deployment-type: split
spec:
  networkInstance:
    name: vpc-midhaul
  cniType: macvlan
  attachmentType: vlan

---
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: e1
  namespace: oai-cu
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.cu
  labels:
    nephio.org/interface: e1
    nephio.org/nf: cu
    nephio.org/deployment-type: split
spec:
  networkInstance:
    name: vpc-cucp-cuup
  cniType: macvlan
  attachmentType: vlan

---
# cu-network-instances.yaml

apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-control
  namespace: oai-cu
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  name: vpc-control
  interfaces:
  - kind: bridgedomain
  pools:
  - name: n2-ipv4-pool
    prefixLength: 24

---
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-midhaul
  namespace: oai-cu
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  name: vpc-midhaul
  interfaces:
  - kind: bridgedomain
  pools:
  - name: f1c-ipv4-pool
    prefixLength: 24

---
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-cucp-cuup
  namespace: oai-cu
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  name: vpc-cucp-cuup
  interfaces:
  - kind: bridgedomain
  pools:
  - name: e1-ipv4-pool
    prefixLength: 24

---
# cu-kptfile

apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: cu-blueprint
  annotations:
    config.kubernetes.io/local-config: "true"
info:
  description: OAI CU deployment package
  
  readinessGates:
  - conditionType: config.injection.WorkloadCluster.workload-cluster
  - conditionType: req.nephio.org.interface.n2
  - conditionType: req.nephio.org.interface.f1c
  - conditionType: req.nephio.org.interface.e1
  - conditionType: ipam.nephio.org.ipclaim.n2
  - conditionType: ipam.nephio.org.ipclaim.f1c
  - conditionType: ipam.nephio.org.ipclaim.e1

pipeline:
  mutators:
  - image: docker.io/nephio/interface-fn:v2.0.0
  - image: docker.io/nephio/nad-fn:v2.0.0
  
  validators:
  - image: gcr.io/kpt-fn/kubeval:v0.3.0
    configMap:
      ignore_missing_schemas: "true"

################################################################################
# DU (Distributed Unit) Package
################################################################################

---
# du-interfaces.yaml
# Interface resources for OAI DU

apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: f1
  namespace: oai-du
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.du
  labels:
    nephio.org/interface: f1
    nephio.org/nf: du
    nephio.org/deployment-type: split
spec:
  networkInstance:
    name: vpc-midhaul
  cniType: macvlan
  attachmentType: vlan

---
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n3
  namespace: oai-du
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.du
  labels:
    nephio.org/interface: n3
    nephio.org/nf: du
    nephio.org/deployment-type: split
spec:
  networkInstance:
    name: vpc-userplane
  cniType: macvlan
  attachmentType: vlan

---
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: ru
  namespace: oai-du
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.NFDeployment.du
  labels:
    nephio.org/interface: ru
    nephio.org/nf: du
    nephio.org/deployment-type: split
spec:
  networkInstance:
    name: vpc-fronthaul
  cniType: macvlan
  attachmentType: vlan

---
# du-network-instances.yaml

apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-midhaul
  namespace: oai-du
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  name: vpc-midhaul
  interfaces:
  - kind: bridgedomain
  pools:
  - name: f1-ipv4-pool
    prefixLength: 24

---
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-userplane
  namespace: oai-du
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  name: vpc-userplane
  interfaces:
  - kind: bridgedomain
  pools:
  - name: n3-ipv4-pool
    prefixLength: 24

---
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata:
  name: vpc-fronthaul
  namespace: oai-du
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  name: vpc-fronthaul
  interfaces:
  - kind: bridgedomain
  pools:
  - name: ru-ipv4-pool
    prefixLength: 24

---
# du-kptfile

apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: du-blueprint
  annotations:
    config.kubernetes.io/local-config: "true"
info:
  description: OAI DU deployment package
  
  readinessGates:
  - conditionType: config.injection.WorkloadCluster.workload-cluster
  - conditionType: req.nephio.org.interface.f1
  - conditionType: req.nephio.org.interface.n3
  - conditionType: req.nephio.org.interface.ru
  - conditionType: ipam.nephio.org.ipclaim.f1
  - conditionType: ipam.nephio.org.ipclaim.n3
  - conditionType: ipam.nephio.org.ipclaim.ru

pipeline:
  mutators:
  - image: docker.io/nephio/interface-fn:v2.0.0
  - image: docker.io/nephio/nad-fn:v2.0.0
  
  validators:
  - image: gcr.io/kpt-fn/kubeval:v0.3.0
    configMap:
      ignore_missing_schemas: "true"

################################################################################
# Common Resources (apply once to management cluster)
################################################################################

---
# ip-pools.yaml
# IP address pools for all networks

apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: control-pool
  namespace: default
spec:
  prefix: 10.1.2.0/24
  networkInstance:
    name: vpc-control
  labels:
    nephio.org/purpose: control
    nephio.org/network-type: n2

---
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: userplane-pool
  namespace: default
spec:
  prefix: 10.1.3.0/24
  networkInstance:
    name: vpc-userplane
  labels:
    nephio.org/purpose: userplane
    nephio.org/network-type: n3

---
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: midhaul-pool
  namespace: default
spec:
  prefix: 10.2.5.0/24
  networkInstance:
    name: vpc-midhaul
  labels:
    nephio.org/purpose: midhaul
    nephio.org/network-type: f1

---
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: fronthaul-pool
  namespace: default
spec:
  prefix: 10.2.6.0/24
  networkInstance:
    name: vpc-fronthaul
  labels:
    nephio.org/purpose: fronthaul
    nephio.org/network-type: ru

---
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: cucp-cuup-pool
  namespace: default
spec:
  prefix: 10.2.1.0/24
  networkInstance:
    name: vpc-cucp-cuup
  labels:
    nephio.org/purpose: cucp-cuup
    nephio.org/network-type: e1

---
# workload-cluster.yaml

apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: edge-cluster-1
  namespace: default
spec:
  clusterName: edge-cluster-1
  cnis:
  - macvlan
  - sriov
  masterInterface: ens3
