---
# Example: Production-ready NAD configuration for SD-Core UPF
# This example assumes:
# - Physical interface ens3 connected to RAN (access network)
# - Physical interface ens4 connected to DN (core network)
# - Access network: 192.168.252.0/24
# - Core network: 192.168.250.0/24
# - ENB subnet: 192.168.2.0/24

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-access-n3
  namespace: omec
  annotations:
    description: "UPF N3 interface for RAN connectivity"
  labels:
    app: sdcore
    component: upf
    interface: access
    5g-interface: n3
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "mtu": 1500,
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.252.3/24",
            "gateway": "192.168.252.1"
          }
        ],
        "routes": [
          {
            "dst": "0.0.0.0/0"
          },
          {
            "dst": "192.168.2.0/24",
            "gw": "192.168.252.1"
          }
        ]
      }
    }

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-core-n6
  namespace: omec
  annotations:
    description: "UPF N6 interface for Data Network connectivity"
  labels:
    app: sdcore
    component: upf
    interface: core
    5g-interface: n6
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens4",
      "mode": "bridge",
      "mtu": 1500,
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.250.3/24",
            "gateway": "192.168.250.1"
          }
        ],
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ]
      }
    }

---
# Optional: NAD for AMF N2 interface if using separate interface
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: amf-n2
  namespace: omec
  annotations:
    description: "AMF N2 interface for control plane to RAN"
  labels:
    app: sdcore
    component: amf
    interface: n2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "mtu": 1500,
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.252.10/24",
            "gateway": "192.168.252.1"
          }
        ],
        "routes": [
          {
            "dst": "192.168.2.0/24",
            "gw": "192.168.252.1"
          }
        ]
      }
    }
